### PR TITLE
added users table

### PR DESCRIPTION
**Pull request by Will-Nollert**
starting out a new branch to build out the users table, seed data, and DB adapters. This successfully creates a table in your local capstone-dev sql database.

### CODE REVIEW

**Comment by Will-Nollert** [comment]
successfully implemented seed data for a single user. I don't have the Phone# row in there yet bc i forgot what we decided to change the data type to but I can patch that easily later. Right now this spins up a Users table and populates that table with one user, Albert.

**Comment by ZVRAJ** [comment]
Will, for some reason i couldn't get it to work with phone INTEGER, so i ended up using VARCHAR(10) in order to move on. Perhaps a question for Daniel.

**Comment by HaydenSmith25** [comment]
Looks good - will leave the phone as-is for now and can discuss more tomorrow.

**Review by HaydenSmith25 — APPROVED** [review]
Looks good - can discuss the phone attribute more tomorrow.

**Pull request merged**
